name: global temps from different models
on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # - name: Install packages
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get and Write Data
        run: Rscript -e 'source("different_models_global_temp.R")'

      - name: Update Datawrapper Chart Notes
        run: |
           curl --request PATCH \
               --url https://api.datawrapper.de/v3/charts/OAVPA \
               --header "Authorization: Bearer ${{ secrets.DW_KEY }}" \
               --header 'content-type: application/json' \
               --data "{ \"metadata\": {\"annotate\": {\"notes\": \"Letzte Datenaktualisierung: $(date +'%d.%m.%Y')\"}}}"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
